#!/bin/bash
set -e

BITS="$HOME/Code/QMK/qmk_bits"
QMK="$HOME/Code/QMK/qmk_firmware"
QMK_UPSTREAM="https://github.com/qmk/qmk_firmware.git"
KEYBOARD="hvr88/keychron_q3"
KEYMAP="hvr88"
KEYBOARD_DIR="$BITS/keyboards/hvr88/keychron_q3"

pull() {
    echo "==> Pulling qmk_bits"
    git -C "$BITS" pull
}

# Clone the latest X.Y.Z release tag from upstream into $QMK.
clone_qmk_release() {
    local tag

    echo "==> Resolving latest QMK release tag from $QMK_UPSTREAM"
    tag=$(git ls-remote --tags --refs "$QMK_UPSTREAM" \
        | awk -F/ '{print $NF}' \
        | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
        | sort -V \
        | tail -1)
    if [ -z "$tag" ]; then
        echo "ERROR: No X.Y.Z release tags found at $QMK_UPSTREAM"
        exit 1
    fi

    echo "==> Latest release: $tag"
    if [ -e "$QMK" ]; then
        echo "==> Removing existing $QMK"
        rm -rf "$QMK"
    fi

    echo "==> Cloning $QMK_UPSTREAM @ $tag → $QMK"
    git clone --recursive --branch "$tag" "$QMK_UPSTREAM" "$QMK"
    echo "==> QMK ready: $(git -C "$QMK" describe --tags --exact-match)"
}

write_usb_identity() {
    local hvr88_ver qmk_ver serial product base_name rand_hex

    hvr88_ver=$(sed -n 's/^#define HVR88_VERSION "\(.*\)"/\1/p' "$KEYBOARD_DIR/hvr88_version.h")
    if [ -z "$hvr88_ver" ]; then
        echo "ERROR: HVR88_VERSION not found in $KEYBOARD_DIR/hvr88_version.h"
        exit 1
    fi

    base_name=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["keyboard_name"])' "$KEYBOARD_DIR/keyboard.json")
    if [ -z "$base_name" ]; then
        echo "ERROR: keyboard_name not found in $KEYBOARD_DIR/keyboard.json"
        exit 1
    fi

    qmk_ver=$(git -C "$QMK" describe --tags --always)
    rand_hex=$(openssl rand -hex 4 | tr '[:lower:]' '[:upper:]')
    serial="${rand_hex} (QMK ${qmk_ver})"
    product="${base_name} (${hvr88_ver})"

    cat > "$KEYBOARD_DIR/serial_number.h" <<EOF
#pragma once

/* Generated by build_flash.sh — do not edit. */
#define SERIAL_NUMBER "${serial}"
#define PRODUCT "${product}"
EOF

    echo "==> USB serial:  $serial"
    echo "==> USB product: $product"
}

copy() {
    echo "==> Copying keyboard and modules"
    mkdir -p "$QMK/keyboards/hvr88"
    cp -R "$BITS/keyboards/hvr88/." "$QMK/keyboards/hvr88/"
    mkdir -p "$QMK/modules"
    cp -R "$BITS/modules/." "$QMK/modules/"
}

# Restore the core to the checked-out release, then apply our patches.
# --3way needs full clone history (no --depth) to merge around upstream edits.
apply_patches() {
    local p

    echo "==> Resetting core to $(git -C "$QMK" describe --tags --always)"
    git -C "$QMK" checkout HEAD -- quantum tmk_core data

    for p in "$BITS"/patches/*.patch; do
        echo "==> Applying $(basename "$p")"
        if ! git -C "$QMK" apply --3way "$p"; then
            echo "ERROR: $(basename "$p") no longer applies cleanly to $(git -C "$QMK" describe --tags --always)"
            echo "Resolve the conflicts in $QMK, then regenerate the patch."
            exit 1
        fi
    done
}

compile() {
    echo "==> Compiling"
    write_usb_identity
    copy
    apply_patches
    cd "$QMK"
    qmk config user.keyboard="$KEYBOARD"
    qmk compile -kb "$KEYBOARD" -km "$KEYMAP"
}

flash() {
    echo "==> Flashing"
    BIN="$QMK/hvr88_keychron_q3_hvr88.bin"

    if [ ! -f "$BIN" ]; then
        echo "ERROR: Firmware binary not found: $BIN"
        echo "Run --compile or --all first."
        exit 1
    fi

    echo "Waiting for STM32 DFU bootloader (Ctrl+C to cancel)..."
    until dfu-util -l 2>/dev/null | grep -q '0483:df11'; do
        sleep 0.5
    done

    dfu-util -a 0 -s 0x08000000:leave -D "$BIN"
}

case "${1:---all}" in
    --qmk)
        clone_qmk_release
        ;;
    --flash)
        flash
        ;;
    --pull)
        pull
        ;;
    --compile)
        pull
        compile
        ;;
    --all)
        pull
        compile
        flash
        ;;
    *)
        echo "Usage: $(basename "$0") [--qmk|--flash|--pull|--compile|--all]"
        exit 1
        ;;
esac
