#!/bin/bash
set -e

BITS="$HOME/Code/QMK/qmk_bits"
QMK="$HOME/Code/QMK/qmk_firmware"
QMK_UPSTREAM="https://github.com/qmk/qmk_firmware.git"
KEYBOARD="hvr88/keychron_q3"
KEYMAP="hvr88"
KEYBOARD_DIR="$BITS/keyboards/hvr88/keychron_q3"

pull() {
    echo "==> Pulling qmk_bits"
    git -C "$BITS" pull
}

# Clone the latest X.Y.Z release tag from upstream into $QMK.
clone_qmk_release() {
    local tag

    echo "==> Resolving latest QMK release tag from $QMK_UPSTREAM"
    tag=$(git ls-remote --tags --refs "$QMK_UPSTREAM" \
        | awk -F/ '{print $NF}' \
        | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
        | sort -V \
        | tail -1)
    if [ -z "$tag" ]; then
        echo "ERROR: No X.Y.Z release tags found at $QMK_UPSTREAM"
        exit 1
    fi

    echo "==> Latest release: $tag"
    if [ -e "$QMK" ]; then
        echo "==> Removing existing $QMK"
        rm -rf "$QMK"
    fi

    echo "==> Cloning $QMK_UPSTREAM @ $tag → $QMK"
    git clone --recursive --branch "$tag" "$QMK_UPSTREAM" "$QMK"
    echo "==> QMK ready: $(git -C "$QMK" describe --tags --exact-match)"
}

write_serial_number() {
    local hvr88_ver qmk_ver serial

    hvr88_ver=$(sed -n 's/^#define HVR88_VERSION "\(.*\)"/\1/p' "$KEYBOARD_DIR/hvr88_version.h")
    if [ -z "$hvr88_ver" ]; then
        echo "ERROR: HVR88_VERSION not found in $KEYBOARD_DIR/hvr88_version.h"
        exit 1
    fi

    qmk_ver=$(git -C "$QMK" describe --tags --always)
    serial="QMK v${qmk_ver}   HVR88 v${hvr88_ver}"

    cat > "$KEYBOARD_DIR/serial_number.h" <<EOF
#pragma once

/* Generated by build_flash.sh — do not edit. */
#define SERIAL_NUMBER "${serial}"
EOF

    echo "==> USB serial: $serial"
}

copy() {
    echo "==> Copying keyboard, modules, data, and core overlays"
    mkdir -p "$QMK/keyboards/hvr88"
    cp -R "$BITS/keyboards/hvr88/." "$QMK/keyboards/hvr88/"
    mkdir -p "$QMK/modules"
    cp -R "$BITS/modules/." "$QMK/modules/"
    mkdir -p "$QMK/data/constants/keycodes"
    cp "$BITS/data/constants/keycodes/"*.hjson "$QMK/data/constants/keycodes/"
    cp "$BITS/quantum/action.c" "$QMK/quantum/action.c"
    cp "$BITS/quantum/action_util.h" "$QMK/quantum/action_util.h"
    cp "$BITS/quantum/action_util.c" "$QMK/quantum/action_util.c"
    cp "$BITS/quantum/keycodes.h" "$QMK/quantum/keycodes.h"
    cp "$BITS/tmk_core/protocol/report.h" "$QMK/tmk_core/protocol/report.h"
    cp "$BITS/tmk_core/protocol/report.c" "$QMK/tmk_core/protocol/report.c"
    cp "$BITS/tmk_core/protocol/usb_descriptor.c" "$QMK/tmk_core/protocol/usb_descriptor.c"
    cp "$BITS/tmk_core/protocol/chibios/usb_report_handling.c" "$QMK/tmk_core/protocol/chibios/usb_report_handling.c"
}

compile() {
    echo "==> Compiling"
    write_serial_number
    copy
    cd "$QMK"
    qmk config user.keyboard="$KEYBOARD"
    qmk compile -kb "$KEYBOARD" -km "$KEYMAP"
}

flash() {
    echo "==> Flashing"
    BIN="$QMK/hvr88_keychron_q3_hvr88.bin"

    if [ ! -f "$BIN" ]; then
        echo "ERROR: Firmware binary not found: $BIN"
        echo "Run --compile or --all first."
        exit 1
    fi

    echo "Waiting for STM32 DFU bootloader (Ctrl+C to cancel)..."
    until dfu-util -l 2>/dev/null | grep -q '0483:df11'; do
        sleep 0.5
    done

    dfu-util -a 0 -s 0x08000000:leave -D "$BIN"
}

case "${1:---all}" in
    --qmk)
        clone_qmk_release
        ;;
    --flash)
        flash
        ;;
    --pull)
        pull
        ;;
    --compile)
        pull
        compile
        ;;
    --all)
        pull
        compile
        flash
        ;;
    *)
        echo "Usage: $(basename "$0") [--qmk|--flash|--pull|--compile|--all]"
        exit 1
        ;;
esac
