#pragma once

#define MAC_FN_QMK_FN_LAYER 1

#define MAC_MISSION_CONTROL_VIA_KEYCODE    QK_KB_0
#define MAC_APPS_VIA_KEYCODE               QK_KB_1
#define MAC_KEY_GLOBE_VIA_KEYCODE          QK_KB_2
#define MAC_KEY_FN_VIA_KEYCODE             QK_KB_3
#define MAC_FN_GLOBE_VIA_KEYCODE           QK_KB_4
#define MAC_FN_QMK_FN_VIA_KEYCODE          QK_KB_5
#define MAC_DICTATION_VIA_KEYCODE          QK_KB_6
#define MAC_DND_VIA_KEYCODE                QK_KB_7
#define MAC_SCRNSHOT_VIA_KEYCODE           QK_KB_8
#define MAC_SCRNSHOT_CB_VIA_KEYCODE        QK_KB_9
#define MAC_SCRNSHOT_AREA_VIA_KEYCODE      QK_KB_10
#define MAC_SCRNSHOT_AREA_CB_VIA_KEYCODE   QK_KB_11
#define MAC_SCRNSHOT_OPT_VIA_KEYCODE       QK_KB_12
#define MAC_SCRNSHOT_OPT_CB_VIA_KEYCODE    QK_KB_13
#define MAC_SIRI_AREA_VIA_KEYCODE          QK_KB_14
#define MAC_SIRI_WINDOW_VIA_KEYCODE        QK_KB_15

#define TAPPING_TERM_PER_KEY
